name: main_workflow

on:
  push:
    branches:
      - nodejs_enviroment_job

jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Jest
        run: npm install jest --legacy-peer-deps

      - name: Run Jest Test
        run: npm run test
        id: jest
        continue-on-error: true
      - name: Fails
        if: steps.jest.outcome != 'success'
        run: echo "Test fallido, se ha producido un error" && exit 1

  enviroment_test_execution:
    runs-on: ubuntu-latest
    needs: [linter-execution, test-execution]
    steps:
      - name: Hello world enviroment
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: '2 DAW'
