name: main_workflow
on:
  push:
    branches:
      - nodejs_linter_job

jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout repository content
      - name: Checkout code
      - uses: actions/checkout@v2
    # Step 2: Linter execution
      - name: Run linter
        uses: github/super-linter@v4
        env:
         DEFAULT_BRANCH: nodejs_linter_job
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         LINTER_RULES_PATH: /
         JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
         VALIDATE_JAVASCRIPT: true
