name: telegram-bot

on:
  push:
    branches:
      - "send_telegram_action"

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./ # Indica la raíz del repositorio para encontrar `action.yml`
        with:
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram_id_user: ${{ secrets.TELEGRAM_ID_USER }}
          user_name: "TuNombre"
